name: VapeMc
version: 1.0.1
main: com.crowed.Main
author: aiCrowedCodes
commands:
  tag:
  kit:
  youtuber:
  ban:
  ipban:
  kick:
  mute:
  unban:
  build:
  set:
  warp:
  set:
  spawn:
  kit:
  bc:
  broadcast:
  chat:
  groupset:
  manutencao:
  rank:
  setrank:
  gm:
  admin:
  setarena:
  fly:
  tp:
  tphere:
  tpall:
  tp:
  tphere:
  tpall:
  evento:
  setevento:
  aplicar:
  lobby:
  ip:
  register:
  login:
  mudarsenha:
  dano:
  pvp:
  skit:
  fake:
  ping:
  tell:
  acc:
  account:
  cps:
  sc:
  report:
  groupyoutuber:
  habilitar:
  desabilitar:
  clan: