name: LunarPvP
author: zNickDEV_
version: 1.0
main: com.lunarpvp.main.Main
commands:
   novidades:
   aviso:
   discord:
   aplicar:
   kits:
   kit:
   setarena:
   gm:
   spawn:
   reiniciar:
   lojakits:
   tag:
   cc:
   warps:
   tp:
   tphere:
   registrar:
   admin:
   logar:
   trocarsenha:
   youtuber:
   build:
   fps:
   report:
   setentregador:
   potion:
   setarcargo:
   sair:
   main:
   kitdiario:
   warps2:
   sortearvip:
   sc:
   tell: